
LINE = '-'
DOTTED = 'o'
LINE_DOTTED = '-o'

# Main colors
BLUE = '#3489b1'
MAGENTA = '#a14383'
YELLOW = '#e5d935'
RED = '#af3c3c'
GREEN = '#54ac43'
ORANGE = '#e88d26'
MID_BLUE = '#3c4baf'

#  Light colors
LIGHT_BLUE = '#99d2ec'
LIGHT_MAGENTA = '#eaa0d2'
LIGHT_YELLOW = '#fdf584'
LIGHT_RED = '#ea8080'
LIGHT_GREEN = '#a6ec98'
LIGHT_ORANGE = '#f7c790'

YUPI_COLORS = [
    BLUE,
    MAGENTA,
    YELLOW,
    RED,
    GREEN,
    ORANGE,
    MID_BLUE
]

YUPI_LIGHT_COLORS = [
    LIGHT_BLUE,
    LIGHT_MAGENTA,
    LIGHT_YELLOW,
    LIGHT_RED,
    LIGHT_GREEN,
    LIGHT_ORANGE
]
