name: Release and Upload Python Package

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install bumpver
      run: pip install bumpver
    - name: Set version with bumpver
      run: bumpver update -n --set-version "${{ github.event.inputs.version }}"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Lock file
      run: uv lock

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest tests

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish -t ${{ secrets.PYPI_RELEASE_TOKEN }}

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: user_info
        message: 'Set version v${{ github.event.inputs.version }}'
        pathspec_error_handling: exitImmediately
        push: "--force"
        tag: 'v${{ github.event.inputs.version }}'
        tag_push: '--force'